### ISSUE TITLE
Doesn't work with Friendica

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [AMNatty/Mastodon-Circles#10]
entered my friendica account and it just says "Something went horribly wrong, couldn't fetch your user." I tried two different Friendica accounts on two different servers, one running a recent release and one running -dev branch. Other applications that use Mastodon API work with Friendica.

**Comment by AMNatty** [comment]
This tool fully runs in the browser, and therefore depends on working CORS headers for it to function at all. I do not know the internals of Friendica, but CORS can likely be configured; and this sadly cannot be fixed within this application without a major change to this application.

If the tool doesn't work regardless of correct CORS configuration, please open a new issue and I'll look into it
