### ISSUE TITLE
fails to resolve handles delegated with /.well-known/host-meta

### ISSUE THREAD

**Issue by easrng** [AMNatty/Mastodon-Circles#5]
if fetching `/.well-known/webfinger` fails you should check `/.well-known/host-meta` for a url template. [the akkoma docs for domain delegation only have you redirect host-meta](https://docs.akkoma.dev/stable/configuration/how_to_serve_another_domain_for_webfinger/#webfinger) and this configuration does occur in the wild (ex. `@em@cassilda.house`, `@purism@librem.one`, probably more)

**Comment by AMNatty** [comment]
I've implemented a fix in https://github.com/AMNatty/Mastodon-Circles/commit/edd46a4a1bc0c117e1366e97bc70bcf140c695c7, however, neither of your cases will work, as they do not have CORS on the `/.well-known/host-meta` endpoint
